FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

# Копирование файлов проекта
COPY /volume1/RiderProjects/TelegramBot /app

# Установка рабочей директории внутри контейнера
WORKDIR /app

# Восстановление зависимостей
RUN dotnet restore

# Сборка проекта
RUN dotnet build -c Release -o out

# Второй этап сборки
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
ENTRYPOINT ["dotnet", "TelegramBot.dll"]