FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
MAINTAINER Pavel Si02 
# Установка рабочей директории внутри контейнера
WORKDIR /app

# Копирование файлов проекта
COPY . /app

# Копирование файлов изображений
COPY Pictures /app
COPY Files /app

# Восстановление зависимостей
RUN dotnet restore

# Сборка проекта
RUN dotnet build -c Release -o out

# Второй этап сборки
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build-env /app/out /app/out
ENTRYPOINT ["dotnet", "out/TelegramBot.dll"]