FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env

# Установка рабочей директории внутри контейнера
WORKDIR /app/TelegramBot

# Копирование файлов проекта
COPY . .

# Копирование файлов изображений
COPY Pictures /app/TelegramBot/Pictures
COPY Files /app/TelegramBot/Files

# Восстановление зависимостей
RUN dotnet restore

# Сборка проекта
RUN dotnet build -c Release -o out

# Второй этап сборки
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
ENTRYPOINT ["dotnet", "TelegramBot.dll"]